// Generated by SIIM - do not edit manually

export enum AalLevel {
  Aal1 = 'aal1',
  Aal2 = 'aal2',
  Aal3 = 'aal3'
}

export enum Action {
  INSERT = 'INSERT',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  TRUNCATE = 'TRUNCATE',
  ERROR = 'ERROR'
}

export enum Buckettype {
  STANDARD = 'STANDARD',
  ANALYTICS = 'ANALYTICS',
  VECTOR = 'VECTOR'
}

export enum CashMovementType {
  CashSale = 'cash_sale',
  CreditPayment = 'credit_payment',
  ManualIncome = 'manual_income',
  ManualExpense = 'manual_expense',
  OwnerWithdrawal = 'owner_withdrawal',
  CashTransferOut = 'cash_transfer_out',
  CashTransferIn = 'cash_transfer_in'
}

export enum CodeChallengeMethod {
  S256 = 's256',
  Plain = 'plain'
}

export enum EqualityOp {
  Eq = 'eq',
  Neq = 'neq',
  Lt = 'lt',
  Lte = 'lte',
  Gt = 'gt',
  Gte = 'gte',
  In = 'in',
  Like = 'like',
  Ilike = 'ilike',
  Is = 'is',
  Match = 'match',
  Imatch = 'imatch',
  Isdistinct = 'isdistinct'
}

export enum FactorStatus {
  Unverified = 'unverified',
  Verified = 'verified'
}

export enum FactorType {
  Totp = 'totp',
  Webauthn = 'webauthn',
  Phone = 'phone'
}

export enum OauthAuthorizationStatus {
  Pending = 'pending',
  Approved = 'approved',
  Denied = 'denied',
  Expired = 'expired'
}

export enum OauthClientType {
  Public = 'public',
  Confidential = 'confidential'
}

export enum OauthRegistrationType {
  Dynamic = 'dynamic',
  Manual = 'manual'
}

export enum OauthResponseType {
  Code = 'code'
}

export enum OneTimeTokenType {
  ConfirmationToken = 'confirmation_token',
  ReauthenticationToken = 'reauthentication_token',
  RecoveryToken = 'recovery_token',
  EmailChangeTokenNew = 'email_change_token_new',
  EmailChangeTokenCurrent = 'email_change_token_current',
  PhoneChangeToken = 'phone_change_token'
}

export enum PaymentType {
  Cash = 'cash',
  Credit = 'credit'
}

export enum TransferStatus {
  Pending = 'pending',
  Sent = 'sent',
  Received = 'received',
  Cancelled = 'cancelled'
}

export enum UserRole {
  Admin = 'admin',
  Manager = 'manager',
  Seller = 'seller'
}

export interface Branches {
  id: string
  name: string
  address?: string
  phone?: string
  is_active: boolean
  created_at: string
  updated_at: string
}

export interface Brands {
  id: string
  name: string
  created_at: string
  updated_at: string
}

export interface CashRegisterMovements {
  id: string
  branch_id: string
  number: number
  type: string
  amount: number
  reference_type?: string
  reference_id?: string
  credit_payment_id?: string
  description?: string
  created_by?: string
  handler_user_id?: string
  created_at: string
}

export interface Categories {
  id: string
  name: string
  brand_id?: string
  created_at: string
  updated_at: string
}

export interface CreditPayments {
  id: string
  credit_id: string
  amount: number
  payment_date: string
  notes?: string
  created_at: string
}

export interface InventoryItems {
  id: string
  product_id: string
  branch_id: string
  quantity: number
  sale_price: number
  created_at: string
  updated_at: string
}

export interface Products {
  id: string
  name: string
  brand_id?: string
  category_id?: string
  unit_id?: string | null
  cost: number
  image_url?: string
  is_active: boolean
  created_at: string
  updated_at: string
}

export interface UnitsOfMeasure {
  id: string
  name: string
  abbreviation?: string
  is_active: boolean
  created_at: string
  updated_at: string
}

export interface PurchaseItems {
  id: string
  purchase_id: string
  product_id: string
  quantity: number
  unit_cost: number
  subtotal: number
  created_at: string
}

export interface Purchases {
  id: string
  branch_id: string
  number: number
  total: number
  notes?: string
  status: string
  created_by?: string
  created_at: string
  updated_at: string
}

export interface SaleItems {
  id: string
  sale_id: string
  product_id: string
  quantity: number
  price: number
  subtotal: number
  created_at: string
}

export interface Sales {
  id: string
  branch_id: string
  number: number
  total: number
  discount: number
  payment_type: string
  cash_amount?: number
  qr_amount?: number
  credit_anticipo?: number
  notes?: string
  created_by?: string
  customer_name?: string
  customer_phone?: string
  customer_id?: string
  created_at: string
  updated_at: string
  deleted_at?: string | null
  deleted_by?: string | null
}

export interface SaleCredits {
  id: string
  sale_id: string
  total: number
  balance: number
  created_by?: string
  created_at: string
  updated_at?: string
}

export interface CreditPayments {
  id: string
  sale_credit_id: string
  amount: number
  payment_type: string
  created_by?: string
  created_at: string
}

export interface Customers {
  id: string
  name: string
  phone?: string
  document_id?: string
  address?: string
  created_at: string
  updated_at: string
}

export interface MenuItems {
  id: string
  group_title: string
  name: string
  href: string
  icon: string
  sort_order: number
  is_active: boolean
  required_role: string | null
  created_at: string
  updated_at: string
}

export interface TransferItems {
  id: string
  transfer_id: string
  product_id: string
  quantity: number
  unit_cost: number
  created_at: string
}

export interface Transfers {
  id: string
  number: number
  from_branch_id: string
  to_branch_id: string
  status: string
  notes?: string
  created_by?: string
  sent_by?: string
  received_by?: string
  created_at: string
  updated_at: string
}

export interface UserBranches {
  id: string
  user_id: string
  branch_id: string
  role: string
  created_at: string
}

export type Database = {
  public: {
    Tables: {
      branches: {
        Row: Branches
        Insert: Partial<Branches>
        Update: Partial<Branches>
      }
      brands: {
        Row: Brands
        Insert: Partial<Brands>
        Update: Partial<Brands>
      }
      cash_register_movements: {
        Row: CashRegisterMovements
        Insert: Partial<CashRegisterMovements>
        Update: Partial<CashRegisterMovements>
      }
      categories: {
        Row: Categories
        Insert: Partial<Categories>
        Update: Partial<Categories>
      }
      credit_payments: {
        Row: CreditPayments
        Insert: Partial<CreditPayments>
        Update: Partial<CreditPayments>
      }
      customers: {
        Row: Customers
        Insert: Partial<Customers>
        Update: Partial<Customers>
      }
      purchase_items: {
        Row: PurchaseItems
        Insert: Partial<PurchaseItems>
        Update: Partial<PurchaseItems>
      }
      purchases: {
        Row: Purchases
        Insert: Partial<Purchases>
        Update: Partial<Purchases>
      }
      sale_credits: {
        Row: SaleCredits
        Insert: Partial<SaleCredits>
        Update: Partial<SaleCredits>
      }
      sale_items: {
        Row: SaleItems
        Insert: Partial<SaleItems>
        Update: Partial<SaleItems>
      }
      sales: {
        Row: Sales
        Insert: Partial<Sales>
        Update: Partial<Sales>
      }
      menu_items: {
        Row: MenuItems
        Insert: Partial<MenuItems>
        Update: Partial<MenuItems>
      }
      transfer_items: {
        Row: TransferItems
        Insert: Partial<TransferItems>
        Update: Partial<TransferItems>
      }
      transfers: {
        Row: Transfers
        Insert: Partial<Transfers>
        Update: Partial<Transfers>
      }
      units_of_measure: {
        Row: UnitsOfMeasure
        Insert: Partial<UnitsOfMeasure>
        Update: Partial<UnitsOfMeasure>
      }
      user_branches: {
        Row: UserBranches
        Insert: Partial<UserBranches>
        Update: Partial<UserBranches>
      }
    }
    Enums: {
      aal_level: AalLevel
      action: Action
      buckettype: Buckettype
      cash_movement_type: CashMovementType
      code_challenge_method: CodeChallengeMethod
      equality_op: EqualityOp
      factor_status: FactorStatus
      factor_type: FactorType
      oauth_authorization_status: OauthAuthorizationStatus
      oauth_client_type: OauthClientType
      oauth_registration_type: OauthRegistrationType
      oauth_response_type: OauthResponseType
      one_time_token_type: OneTimeTokenType
      payment_type: PaymentType
      transfer_status: TransferStatus
      user_role: UserRole
    }
  }
}
